version: '3.6'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
